#!/bin/bash

# replace with your compiled version of sander
if [ -z "$TESTsander" ]; then
    TESTsander="/home8/larry/ips-pgm/bin/sander.MPI"
fi

if [ -z "$DO_PARALLEL" ]; then
    DO_PARALLEL="mpirun -np 16"
fi

# Prepare input file
cat > mdin <<EOF
 single point calc.
 &cntrl
   imin=0, nstlim=1000000,
   irest=1, ntx=5,
   ntt=1, temp0=300,
   ntb=1, ntp=0,
   ntc=2, ntf=2, tol=0.000001,
   cut=10.,
   ntpr=1000, ntwr=1000, ntwx=1000,
   dt=0.001,
   ipgm=1,
 /
 &ewald
  skinnb=0.,ew_coeff=0.4,nfft1=50,nfft2=50,nfft3=50,order=8,vdwmeth=0
 /
 &pol_gauss
   pol_gauss_verbose=0,ee_dsum_cut=10.0,
   dipole_scf_tol=0.0001,dipole_scf_init=3,dipole_scf_init_order=2,dipole_scf_init_step=4,
   scf_solv_opt=3,scf_sor_niter=100,scf_sor_coefficient=0.65,
   scf_cg_niter=50,scf_local_niter=3,scf_local_cut=4.0
 /
EOF

$DO_PARALLEL $TESTsander -O -i mdin -p prmtop -c restrt0  -o pgm-pme.out 